# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build immich-import-control`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t immich-import-control`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system immich-import-control && \
          adduser --system -G immich-import-control immich-import-control

COPY dist/apps/immich-import-control immich-import-control/
RUN chown -R immich-import-control:immich-import-control .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix immich-import-control --omit=dev -f install

CMD [ "node", "immich-import-control" ]
